# generated by datamodel-codegen:
#   filename:  backtest_config.json
#   timestamp: 2026-06-09T15:41:11+00:00

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from . import cost_config as cost_config_1


class WalkForward(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    train_window_months: int = Field(..., ge=1)
    test_window_months: int = Field(..., ge=1)
    step_months: int = Field(..., ge=1)


class BacktestConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: date = Field(..., description="回測起日")
    end: date = Field(..., description="回測迄日")
    rebalance: Literal["monthly", "quarterly", "semiannual"] = Field(
        ..., description="再平衡頻率 (月~半年)"
    )
    fill: Literal["next_open", "next_close", "same_close"] = Field(
        ..., description="成交時點模型"
    )
    mode: Literal["gross", "net"] = Field(
        ..., description="報酬模式;net 含 cost_config"
    )
    cost_config: cost_config_1.CostConfig | None = None
    walk_forward: WalkForward
    seed: int = Field(..., description="隨機種子 (可重現)")
    data_version: str = Field(..., description="DataProvider 資料版本標籤 (可重現)")
    engine: Literal["vectorized", "event_driven"] | None = Field(
        "vectorized", description="引擎實作;A0 預設 vectorized,event_driven 為未來預留"
    )
