# generated by datamodel-codegen:
#   filename:  cost_config.json
#   timestamp: 2026-06-09T15:41:11+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class CostConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commission_bps: float = Field(
        ..., description="交易手續費 (basis points, 雙邊)", ge=0.0
    )
    slippage_bps: float = Field(..., description="滑價 (basis points)", ge=0.0)
    tw_transaction_tax_bps: float = Field(..., description="台股證交稅 (賣出)", ge=0.0)
    us_dividend_withholding_pct: float = Field(
        ..., description="美股股息預扣稅率", ge=0.0, le=1.0
    )
    fx_spread_bps: float = Field(..., description="USD/TWD 換匯點差", ge=0.0)
