# generated by datamodel-codegen:
#   filename:  performance_metrics.json
#   timestamp: 2026-06-10T22:28:25+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class PerformanceMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cumulative_return: float
    annualized_return: float
    annualized_vol: float = Field(..., ge=0.0)
    max_drawdown: float = Field(..., description="最大回撤 (<=0)", le=0.0)
    sharpe: float
    turnover: float = Field(..., ge=0.0)
    basis: Literal["gross", "net"] = Field(..., description="成本基礎")
    segment: Literal["in_sample", "out_of_sample", "full"] = Field(
        ..., description="區段;leaderboard 比較須用 out_of_sample"
    )
